# Assuming the .travis.yml file is in the project directory, and there is a separate sub-directory for each service
# Use either `docker-compose` or individual `docker build` commands
# Build
- docker build -t udagram-api-feed ./api-feed
- docker build -t udagram-api-user ./api-user
- docker build -t udagram-frontend ./frontend

# Do similar for other three images

# Tagging
- docker tag udagram-api-feed e596aaaa7545/udagram-api-feed:v1
- docker tag udagram-api-user e596aaaa7545/udagram-api-user:v1
- docker tag udagram-frontend e596aaaa7545/udagram-api-frontend:v1

# Do similar for other three images

# Push
# Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push e596aaaa7545/udagram-api-feed:v1
# Do similar for other three images