[
  "docker build -t udagram-api-feed ./api-feed", 
  "docker build -t udagram-api-user ./api-user", 
  "docker build -t udagram-frontend ./frontend", 
  "docker tag udagram-api-feed e596aaaa7545/udagram-api-feed:v1", 
  "docker tag udagram-api-user e596aaaa7545/udagram-api-user:v1", 
  "docker tag udagram-frontend e596aaaa7545/udagram-api-frontend:v1", 
  "echo \"$DOCKER_PASSWORD\" | docker login -u \"$DOCKER_USERNAME\" --password-stdin", 
  "docker push e596aaaa7545/udagram-api-feed:v1"
]